version: '3.3'

networks:
  local-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - local-network
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3006:3000
    networks:
      - local-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - local-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - local-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    networks:
      - local-network