global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-service-a-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8091"]
        labels:
          application: "api-service-a"